[package]
name = "fractals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.3"
image = "0.25.1"
human-panic = "2.0.0"
rayon = "1.10.0"
clap = "4.5.7"